# Generated by Django 5.1.4 on 2026-06-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_userplacestate_last_seen_route'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='place',
            new_name='places_plac_categor_c1a963_idx',
            old_name='places_plac_categor_e4ca4c_idx',
        ),
        migrations.RenameIndex(
            model_name='place',
            new_name='places_plac_source_252cf6_idx',
            old_name='places_plac_source__690193_idx',
        ),
        migrations.RenameIndex(
            model_name='userplacestate',
            new_name='places_user_user_id_dcef0b_idx',
            old_name='places_user_user_id_bae298_idx',
        ),
        migrations.RenameIndex(
            model_name='userplacestate',
            new_name='places_user_user_id_e6c8d7_idx',
            old_name='places_user_user_id_93f5d6_idx',
        ),
    ]
