TOUR_ROUTE_CATEGORY_CULTURE = "culture"
TOUR_ROUTE_CATEGORY_PARK = "park"
TOUR_ROUTE_CATEGORY_FOOD = "food"

TOUR_ROUTE_POI_CATEGORIES = (
    TOUR_ROUTE_CATEGORY_CULTURE,
    TOUR_ROUTE_CATEGORY_PARK,
    TOUR_ROUTE_CATEGORY_FOOD,
)

TOUR_ROUTE_CATEGORY_PRIORITY = {
    TOUR_ROUTE_CATEGORY_CULTURE: 0,
    TOUR_ROUTE_CATEGORY_PARK: 1,
    TOUR_ROUTE_CATEGORY_FOOD: 2,
}

TOUR_ROUTE_MODE_TOUR = "tour"
TOUR_ROUTE_MODE_DIRECT_FALLBACK = "direct_fallback"

TOUR_ROUTE_STOP_STATE_ACTIVE = "active"
TOUR_ROUTE_STOP_STATE_VISITED = "visited"

TOUR_ROUTE_STOP_STATES = (
    TOUR_ROUTE_STOP_STATE_ACTIVE,
    TOUR_ROUTE_STOP_STATE_VISITED,
)

TOUR_ROUTE_DETAIL_STATUS_PENDING = "pending"
TOUR_ROUTE_DETAIL_STATUS_COMPLETE = "complete"
TOUR_ROUTE_DETAIL_STATUS_UNAVAILABLE = "unavailable"
TOUR_ROUTE_DETAIL_STATUS_ERROR = "error"
