from __future__ import annotations

from core.domain import (
    DETAIL_STATUS_COMPLETE,
    DETAIL_STATUS_ERROR,
    DETAIL_STATUS_PENDING,
    DETAIL_STATUS_UNAVAILABLE,
    PLACE_CATEGORY_CULTURE,
    PLACE_CATEGORY_FOOD,
    PLACE_CATEGORY_PARK,
    PLACE_CATEGORY_PRIORITY,
    ROUTE_MODE_DIRECT_FALLBACK,
    ROUTE_MODE_TOUR,
    ROUTE_STOP_STATE_ACTIVE,
    ROUTE_STOP_STATE_EXCLUDED,
    ROUTE_STOP_STATE_VISITED,
    ROUTE_STOP_STATES_PUBLIC,
)

TOUR_ROUTE_CATEGORY_CULTURE = PLACE_CATEGORY_CULTURE
TOUR_ROUTE_CATEGORY_PARK = PLACE_CATEGORY_PARK
TOUR_ROUTE_CATEGORY_FOOD = PLACE_CATEGORY_FOOD

TOUR_ROUTE_POI_CATEGORIES = (
    TOUR_ROUTE_CATEGORY_CULTURE,
    TOUR_ROUTE_CATEGORY_PARK,
    TOUR_ROUTE_CATEGORY_FOOD,
)

TOUR_ROUTE_CATEGORY_PRIORITY = PLACE_CATEGORY_PRIORITY

TOUR_ROUTE_MODE_TOUR = ROUTE_MODE_TOUR
TOUR_ROUTE_MODE_DIRECT_FALLBACK = ROUTE_MODE_DIRECT_FALLBACK

TOUR_ROUTE_STOP_STATE_ACTIVE = ROUTE_STOP_STATE_ACTIVE
TOUR_ROUTE_STOP_STATE_VISITED = ROUTE_STOP_STATE_VISITED
TOUR_ROUTE_STOP_STATE_EXCLUDED = ROUTE_STOP_STATE_EXCLUDED

TOUR_ROUTE_STOP_STATES = ROUTE_STOP_STATES_PUBLIC

TOUR_ROUTE_DETAIL_STATUS_PENDING = DETAIL_STATUS_PENDING
TOUR_ROUTE_DETAIL_STATUS_COMPLETE = DETAIL_STATUS_COMPLETE
TOUR_ROUTE_DETAIL_STATUS_UNAVAILABLE = DETAIL_STATUS_UNAVAILABLE
TOUR_ROUTE_DETAIL_STATUS_ERROR = DETAIL_STATUS_ERROR
