# Generated by Django 5.1.4 on 2026-05-27 00:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('transport_mode', models.CharField(choices=[('transit', 'Transporte público'), ('rideshare', 'Aplicativo de carro'), ('walking', 'A pé'), ('driving', 'Carro próprio')], default='walking', max_length=16)),
                ('distance_m', models.PositiveIntegerField()),
                ('duration_s', models.PositiveIntegerField()),
                ('polyline', models.TextField(help_text='Encoded polyline ou JSON LineString devolvido pelo provedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='routes_rout_user_id_983ccb_idx')],
            },
        ),
    ]
