# Generated by Django 5.1.4 on 2026-06-01 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('origin_query', models.CharField(blank=True, max_length=255)),
                ('destination_query', models.CharField(blank=True, max_length=255)),
                ('search_payload', models.JSONField(blank=True, default=dict)),
                ('route_payload', models.JSONField(blank=True, default=dict)),
                ('map_payload', models.JSONField(blank=True, default=dict)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache de rota turistica',
                'verbose_name_plural': 'Caches de rotas turisticas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedTourRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_query', models.CharField(blank=True, max_length=255)),
                ('destination_query', models.CharField(blank=True, max_length=255)),
                ('origin_label', models.CharField(blank=True, max_length=255)),
                ('destination_label', models.CharField(blank=True, max_length=255)),
                ('excluded_stop_ids', models.JSONField(blank=True, default=list)),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('route_payload', models.JSONField(blank=True, default=dict)),
                ('map_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tour_routes', to=settings.AUTH_USER_MODEL)),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_routes', to='tour_routes.tourroutecache')),
            ],
            options={
                'verbose_name': 'Rota turistica salva',
                'verbose_name_plural': 'Rotas turisticas salvas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tour_routes_user_id_f77568_idx')],
            },
        ),
    ]
