# Generated by Django 5.1.4 on 2026-06-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour_routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedtourroute",
            name="visited_stop_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="TourRoutePoiDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=32)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("source", models.CharField(default="overpass", max_length=32)),
                ("osm_type", models.CharField(blank=True, max_length=16)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("wikidata_id", models.CharField(blank=True, max_length=64)),
                ("wikipedia_title", models.CharField(blank=True, max_length=255)),
                ("address", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("opening_hours", models.CharField(blank=True, max_length=255)),
                ("detail_status", models.CharField(default="pending", max_length=32)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("details_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Detalhe de ponto turistico",
                "verbose_name_plural": "Detalhes de pontos turisticos",
                "ordering": ["name"],
            },
        ),
    ]
