# Generated by Django 5.1.4 on 2026-06-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tourroute',
            new_name='tour_routes_user_id_4dcc7c_idx',
            old_name='tour_routes_user_id_6eeefe_idx',
        ),
        migrations.RenameIndex(
            model_name='tourroutestop',
            new_name='tour_routes_route_i_b58b5b_idx',
            old_name='tour_routes_route_i_7f59de_idx',
        ),
        migrations.RenameIndex(
            model_name='tourroutestop',
            new_name='tour_routes_route_i_e13644_idx',
            old_name='tour_routes_route_i_b74478_idx',
        ),
    ]
