# Generated by Django 5.1.4 on 2026-06-02 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tour_routes", "0002_savedtourroute_visited_stop_ids_tourroutepoidetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTourPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_visited", models.BooleanField(default=False)),
                ("visited_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("seen_count", models.PositiveIntegerField(default=1)),
                (
                    "last_seen_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seen_places",
                        to="tour_routes.savedtourroute",
                    ),
                ),
                (
                    "poi_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_places",
                        to="tour_routes.tourroutepoidetail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_places",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lugar de rota do usuario",
                "verbose_name_plural": "Lugares de rota do usuario",
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_seen_at"],
                        name="tour_routes_user_id_6568bb_idx",
                    ),
                    models.Index(
                        fields=["user", "is_visited"],
                        name="tour_routes_user_id_ef56f2_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usertourplace",
            constraint=models.UniqueConstraint(
                fields=("user", "poi_detail"),
                name="tour_routes_unique_user_poi_place",
            ),
        ),
    ]
