# Generated by Django 5.1.4 on 2026-06-05 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tour_routes", "0002_rename_tour_routes_user_id_6eeefe_idx_tour_routes_user_id_4dcc7c_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRouteSearchPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("include_culture", models.BooleanField(default=True)),
                ("include_park", models.BooleanField(default=True)),
                ("include_food", models.BooleanField(default=True)),
                (
                    "poi_spacing_m",
                    models.PositiveSmallIntegerField(
                        choices=[(75, "75 m"), (100, "100 m"), (150, "150 m")],
                        default=100,
                    ),
                ),
                (
                    "max_search_radius_m",
                    models.PositiveSmallIntegerField(
                        choices=[(150, "150 m"), (250, "250 m"), (400, "400 m")],
                        default=250,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="route_search_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User route search preference",
                "verbose_name_plural": "User route search preferences",
            },
        ),
    ]
