# Generated by Django 5.1.4 on 2026-05-27 00:14

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=tickets.models._generate_ticket_code, max_length=32, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('total_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('valid', 'Válido'), ('used', 'Utilizado'), ('expired', 'Expirado')], default='valid', max_length=16)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['user', '-purchased_at'], name='tickets_tic_user_id_1cfc1e_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx')],
            },
        ),
    ]
